# Generated by Django 6.0.4 on 2026-08-11 07:30

from django.db import migrations, models

import horilla.utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_businesshour_time_zone_alter_company_time_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="horillauser",
            name="calendar_system",
            field=models.CharField(
                choices=horilla.utils.choices.CALENDAR_SYSTEM_CHOICES,
                default="jalali",
                help_text="Choose Shamsi (Jalali) or Gregorian dates when your language is Persian.",
                max_length=20,
                verbose_name="Calendar System",
            ),
        ),
    ]
