# Generated by Django 6.0.4 on 2026-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_activetab_created_at_alter_activetab_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclebin',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycle_delete', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By'),
        ),
        migrations.AlterField(
            model_name='recyclebin',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Model Name'),
        ),
    ]
