# Generated by Django 6.0.4 on 2026-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approvalcondition_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldecision',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='decided_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Decided At'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decided By'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalinstance', verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='approvaldecision',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalstep', verbose_name='Step'),
        ),
    ]
