# Generated by Django 6.0.4 on 2026-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_created_at_alter_campaign_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to=settings.AUTH_USER_MODEL, verbose_name='Campaign Owner'),
        ),
    ]
