# Generated by Django 6.0 on 2026-02-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0010_alter_kanbangroupby_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horillauser',
            name='enable_ai',
            field=models.BooleanField(default=False, help_text='Toggle the AI assistant feature across the system', verbose_name='Enable CRM AI'),
        ),
    ]
