# Generated by Django 6.0.4 on 2026-09-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_created_at_alter_contact_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Contact Owner'),
        ),
    ]
