# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.db.models.deletion
import horilla_crm.dashboards.methods
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("horilla_core", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componentcriteria",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="componentcriteria",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="componentcriteria",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="dashboard_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dashboard Owner",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="favourited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favourited By",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="component_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Component Owner",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="dashboards.dashboard",
                verbose_name="Dashboard",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="module",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=horilla_crm.dashboards.methods.limit_content_types,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.horillacontenttype",
                verbose_name="Module",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="reports",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to="reports.report",
                verbose_name="Reports",
            ),
        ),
        migrations.AddField(
            model_name="dashboardcomponent",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="componentcriteria",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="dashboards.dashboardcomponent",
                verbose_name="Component",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="favourited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite_folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favourited By",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="folder_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Folder Owner",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="parent_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="dashboards.dashboardfolder",
                verbose_name="Folder",
            ),
        ),
        migrations.AddField(
            model_name="dashboardfolder",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to="dashboards.dashboardfolder",
                verbose_name="Folder",
            ),
        ),
    ]
