# Generated by Django 6.0.4 on 2026-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_horillamail_created_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='horillamail',
                    name='mail_status',
                    field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Mail Status'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS "mail_horillamail_mail_status_14de5959" ON "mail_horillamail" ("mail_status")',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='horillamail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='horillamail',
            name='to',
            field=models.TextField(blank=True, help_text='Comma separated recipient email addresses', verbose_name='Send To'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='last_refreshed',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Token Last Refreshed'),
        ),
        migrations.AlterField(
            model_name='horillamailconfiguration',
            name='use_dynamic_display_name',
            field=models.BooleanField(default=True, help_text='By enabling this the display name will take from who triggered the mail', verbose_name='Dynamic Display Name'),
        ),
    ]
