# Generated by Django 6.0.4 on 2026-09-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_created_at_alter_account_is_active_and_more'),
        ('opportunities', '0004_alter_defaultopportunitymember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_account', to='accounts.account', verbose_name='Account'),
        ),
    ]
