# Generated by Django 6.0 on 2026-02-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Response Payload')),
                ('model_id', models.CharField(max_length=100, verbose_name='Model ID')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='Latency (ms)')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Estimated Cost ($)')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
